/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class win_yulongsun_androidsample_jni_JniTest */

#ifndef _Included_win_yulongsun_androidsample_jni_JniTest
#define _Included_win_yulongsun_androidsample_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     win_yulongsun_androidsample_jni_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_win_yulongsun_androidsample_jni_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     win_yulongsun_androidsample_jni_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_win_yulongsun_androidsample_jni_JniTest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
